### ISSUE TITLE
origin.spec changelog no longer informative

### ISSUE THREAD

**Issue by jupierce** [openshift/aos-cd-jobs#1045]
Some time in Nov, the changelog tito was managing in origin.spec stopped including information about merges. 

Compare:
boring: https://github.com/openshift/ose/blob/5d2074caf3acd8828599be460f06a11cb1e494f9/origin.spec#L609
interesting: https://github.com/openshift/ose/blob/5d2074caf3acd8828599be460f06a11cb1e494f9/origin.spec#L711

Commits are being merged, but tito doesn't seem to carry that information into the changelog any more. Has something changed?

**Comment by adammhaile** [comment]
This is what broke it: https://github.com/openshift/aos-cd-jobs/commit/1da1e9cc034de5a4ece291f4cb2d1d2ab10073f5#diff-4afa940aacab03ebeba0c98c8cc67d64

--changelog overrides auto generating the changelog

**Comment by jupierce** [comment]
Changelog is back! Thanks @adammhaile .
