### ISSUE TITLE
Jobs based on origin_minimal are not appearing on openshift-gce-devel.appspot.com

### ISSUE THREAD

**Issue by bbguimaraes** [openshift/aos-cd-jobs#1269]
E.g.: https://openshift-gce-devel.appspot.com/pr/18988

It may be because it is missing these steps:

https://github.com/openshift/aos-cd-jobs/blob/18e0ec1809bceb719f768921e8bf56babbd1840b/sjb/config/common/test_cases/origin.yml#L46-L113

**Comment by bbguimaraes** [comment]
@stevekuznetsov

**Comment by stevekuznetsov** [comment]
The callout to `initupload` in the `sync:` block does those uploads -- are those jobs on `origin_minimal` but somehow not running the sync?

**Comment by bbguimaraes** [comment]
Confirmed that it's working, but commit SHAs are not recorded anymore, causing
new jobs to be grouped under the "unknown" column.

`test_pull_request_origin_cross`, the only job that still recorded them, has
been updated, so the grouping will get a little better as new jobs run.
