### ISSUE TITLE
No clear way to retest travis or ha-master tests

### ISSUE THREAD

**Issue by ewolinetz** [openshift/aos-cd-jobs#1306]
Issue seen with https://github.com/openshift/openshift-ansible/pull/7984
When travis and ha-master tests failed there was no way to restart the tests with commands.

@stevekuznetsov

**Comment by stevekuznetsov** [comment]
Travis can be restarted by an admin in the Travis console and unfortunately without an API that's the best we can do. The HA test seems to have been reconfigured? This should not reoccur.

/clone
