### ISSUE TITLE
service-catalog image not pushing to v3.10, v3.10.0

### ISSUE THREAD

**Issue by smarterclayton** [openshift/aos-cd-jobs#1330]
Looks like service-catalog repo hack/push-release or the job needs to be updated to run the same as the other jobs.  (basically, publishes master to the described tag version).

**Comment by jpeeler** [comment]
I assume https://github.com/openshift/release/pull/820/ is related? I'm not sure what exactly needs to be done here yet.

**Comment by jpeeler** [comment]
I see that the latest tag isn't pushing, but the v3.10 images seem to be fresh. Were those manually done yesterday?

**Comment by jpeeler** [comment]
For full context, I'm seeing this (from https://ci.openshift.redhat.com/jenkins/job/push_origin_release/2827/console):
```
+ hack/push-release.sh

[WARNING] Pushing local :latest images to docker.io/openshift/*:latest,:v0.1,:v0.1.14
Error response from daemon: no such id: openshift/origin-service-catalog:latest
[ERROR] PID 25963: hack/push-release.sh:70: `docker tag "openshift/${image}:${source_tag}" "${OS_PUSH_BASE_REGISTRY-}${OS_PUSH_BASE_REPO}${image}${tag}"` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/push-release.sh:70: `docker tag "openshift/${image}:${source_tag}" "${OS_PUSH_BASE_REGISTRY-}${OS_PUSH_BASE_REPO}${image}${tag}"`
[INFO]   Exiting with code 1.
++ export status=FAILURE
++ status=FAILURE
```
I was planning on origin images keeping the upstream tag (docker uses build timestamps for determining newer images, right?) And with that mindset I'm not sure what's wrong with the above. Please advise if catalog needs to do additional tagging to have v3.x builds.

**Comment by jpeeler** [comment]
The pushes are based on the tags and the tags have been changed to conform to openshift's 3.x versioning. This issue can be closed.
