### ISSUE TITLE
service-catalog missing repo sync 

### ISSUE THREAD

**Issue by jpeeler** [openshift/aos-cd-jobs#1345]
Adding service-catalog to at least one more sync section will be necessary, I suspect sjb/config/common/test_cases/origin_release_with_ecosystem.yml is one location. However, I see that repo sync lists are scattered throughout many files:

Grep of origin-web-console-server repo listing:
https://rawgit.com/jpeeler/f95ad8e32d7da7289dbc1ad18506be0b/raw/4b75fb1b38e7f1a88a5a8d0714e8b1cd39282e5f/origin-web-console-server.html

Current service-catalog listing, including origin_release_with_ecosystem.yml:
https://rawgit.com/jpeeler/c8223b0718048bd29b7d9dae16570d0a/raw/714b63ad6bd332a236db62ca360ea4e8fbe7def6/service-catalog.html

Does it hurt to just put catalog everywhere? I hesitated since I noticed that the sync lists are not simply copied everywhere.

@stevekuznetsov would like your expertise on this. If I need to simply trace through all the tests and figure out where the additional catalog syncs needs to occur I can do that, but was hoping I wouldn't have to.

**Comment by stevekuznetsov** [comment]
Generally we override `sync` at the last part of the job tree, so `origin_release_with_ecosystem` could declare something but it is up to child jobs to determine their dependencies. This allows for the branch-specific child jobs (`_39`) to be declarative about all of their dependencies. You can use `sjb/children.sh` and `sjb/parents.sh` to navigate the tree.
