### ISSUE TITLE
extended tests run in go 1.6

### ISSUE THREAD

**Issue by jim-minter** [openshift/aos-cd-jobs#137]
Similar to the fix in https://github.com/openshift/aos-cd-jobs/pull/102 , a fix is needed to compile extended tests using go 1.7.

**Comment by stevekuznetsov** [comment]
@jim-minter which jobs are mis-compiling? `build-rpm-release.sh` should be run inside of `hack/env` for the `test_pull_request_origin_extended_conformance_{gce,install}` jobs.
