### ISSUE TITLE
install origin failing consistently for certain jobs

### ISSUE THREAD

**Issue by gabemontero** [openshift/aos-cd-jobs#1410]
See jobs 141, 142, and 143 for https://ci.openshift.redhat.com/jenkins/view/All/job/test_pull_request_jenkins_sync_plugin/

This job last passed install origins on May 22

See https://ci.openshift.redhat.com/jenkins/view/All/job/test_branch_origin_extended_image_ecosystem/492/

See https://ci.openshift.redhat.com/jenkins/view/All/job/test_branch_origin_extended_image_registry/217/

I see quite a few commits on May 23 and 24 ... is it possible one of those introduced a regression?

@openshift/sig-continuous-delivery @openshift/sig-continuous-infrastructure ptal

**Comment by gabemontero** [comment]
@openshift/sig-developer-experience fyi

**Comment by smarterclayton** [comment]
This looks like something with service catalog and images @pmorie @sdodson had been looking at something similar.

**Comment by sdodson** [comment]
It's expecting that `openshift/origin-service-catalog:8ac6446` because we're setting 'oreg_url=openshift/origin-${component}:8ac6446' which will work for images built during the job but won't work for images built outside of the job. Problem introduced in https://github.com/openshift/openshift-ansible/pull/8479 not sure the correct way to fix this short of overriding a bunch of variables in CI jobs. What we're doing is the right thing to do for end users but the wrong thing for CI.

@michaelgugino thoughts?

**Comment by michaelgugino** [comment]
We either need to build service-catalog and related components in the same manner we build everything else, or we need to set openshift_service_catalog_image in this job.

**Comment by gabemontero** [comment]
bump @michaelgugino @sdodson - any ETA for when a fix might be coming, or at least an ETA on when a decision on which fix strategy to employ?

this is currently blocking the nightly regression runs for image registry, app development related images from the sclorg, and the build component.

I would add some labels indicating the blocking nature of this, but I don't appear to have permission to do that for issues in this repo.

thanks

**Comment by gabemontero** [comment]
@adambkaplan /cc

**Comment by gabemontero** [comment]
Did a little digging based on the insights from @sdodson and @michaelgugino to at least better familiarize myself with what is going on.  

Ended up focusing on https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/common/test_cases/origin_installed_release.yml which is what all of our affected jobs cite as their parent, where these jobs do not build the origin images as @sdodson noted.

1) so at https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/common/test_cases/origin_installed_release.yml#L37-L38 we get the latest commit from aos-cd-jobs to populate `ORIGIN_COMMIT`

2) at https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/common/test_cases/origin_installed_release.yml#L37-L38 we use `ORIGIN_COMMIT` to set `oreg_url`

Now I have only scanned briefly, but I see a fair amount of defaulting on the openshift-ansible side, including the `oreg_url` value.

If our affected jobs extended a derivative of https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/common/test_cases/origin_installed_release.yml (where if practical refactor that file with some new ones to maximize sharing) that either
a) does not set oreg_url on the call to `ansible-playbook`
b) or sets ORIGIN_COMMIT to `latest`

We would effectively get "very recent" versions of the openshift images, still be able to successfully get origin installed, up and running etc., and thus satisfy our regression testing needs?

Or has my brief scans overlooked key roadblocks?

thanks

**Comment by stevekuznetsov** [comment]
We chose the SHA approach as we want to be certain that we are integrating the latest built versions of these images. If we are using `:latest` we would, for instance, in the cases where image GC was nuking component images, pull other versions from Docker Hub or other registries configured in the AMI... and end up with an unintelligible test as we have no control over the versions of the images being used. We either need to build the missing image or tag it in.

**Comment by gabemontero** [comment]
Understood @stevekuznetsov , but the path to building the missing image or tagging it in is unclear or undesirable from my knowledge of things, and at this point, validation against "some version" vs. no validation attempts is appearing more and more like sufficient progress, at least to me.  Part of that though is a an assumption that there is a possible short term solution and then a longer term solution.  

On tagging in ... presumably the image with the specific sha is not anywhere accessible, which is why it can't be accessed to be tagged in .... or am I missing something obvious ?

On building ... I don't see a yml file in aos-cd-jobs specific to building the svc cat images.  Adding specific logic in each of our failing jobs to build it seems wrong, as does adding that logic to origin_installed_release.yml .... correct?

So for building, though it involves extra work to the point of overkill perhaps, does it make sense to change these jobs to have origin_release.yml as the parent instead of openshift_installed_release.yml, where the full build that would be initiated would create all the images possibly needed (now or in the future) at that requisite sha's ?

**Comment by stevekuznetsov** [comment]
Tagging in would just take `:latest` from wherever and tag it with the SHA. The rest of the jobs seem to run with `origin_release.yml`, right, as they do all the building necessary in the job itself. This is definitely slower and more resource intensive but for daily runs it should be a minimal impact, right? We aim to have "stable latest" streams we can pull from for jobs soon as well that will make incremental builds simple/

**Comment by gabemontero** [comment]
On Thu, May 31, 2018 at 12:27 PM, Steve Kuznetsov <notifications@github.com>
wrote:

> Tagging in would just take :latest from wherever and tag it with the SHA.
>
Ah I see what you mean now - thanks ... presumably tagging with the SHA
protects from the image pruning / GC, right?

> The rest of the jobs seem to run with origin_release.yml, right,
>

Yep, just searched and confirmed only our jobs leverage
origin_installed_release.yml ... hadn't realized that previously ... so
yeah, we could customize
this to tag the image(s) in question


> as they do all the building necessary in the job itself. This is
> definitely slower and more resource intensive but for daily runs it should
> be a minimal impact, right?
>
To a point ... the jobs are crazy slow as hell already ... a debate could
be had, but it is another viable short term option

> We aim to have "stable latest" streams we can pull from for jobs soon as
> well that will make incremental builds simple/
>

Ah good to know thanks ...

OK, we'll discuss on the dev ex side and decide which approach to take ...
thanks again @skuznets
