### ISSUE TITLE
adding cri-o yum repos to rhel7next.sh

### ISSUE THREAD

**Issue by lsm5** [openshift/aos-cd-jobs#1438]
@stevekuznetsov @jupierce @runcom @ashcrow  RE: getting cri-o and cri-tools into dockertested, can we include internal brewweb links in rhel7next.sh ? If yes, how should I include it exactly? Should all different branches go into the script together, or do I issue PRs to build/ose3.x branch for rhaos-3.x branch? Or, instead of internal repos, I could just add CentOS PaaS SIG repos where i'm just rebuilding the rhaos sources.

**Comment by jupierce** [comment]
@lsm5 rhel7next.sh runs within the VPN, so it can include brew links. Only the master branch matters for the purposes of this script.

**Comment by lsm5** [comment]
@jupierce so RE: cri-o and cri-tools, it gets built for multiple branches rhaos-3.[8,9,10]-rhel-7. And these end up in different yum repos. What I'm wondering about is for example: do all of openshift 3.8, 3.9 and 3.10 use the master branch itself to get their yum repos configured?

IOW, if I were to include the cri-o repos, would something like this in the master branch rhel7next.sh suffice:

LATEST_CRIO_1.8=$BASE_DIR/$PATH_TO_1.8
LATEST_CRIO_1.9=$BASE_DIR/$PATH_TO_1.9
LATEST_CRIO_1.10=$BASE_DIR/$PATH_TO_1.10
