### ISSUE TITLE
CI failure due to tito exception - test_pull_request_origin_extended_conformance_gce_39

### ISSUE THREAD

**Issue by jpeeler** [openshift/aos-cd-jobs#1458]
(test_pull_request_origin_extended_conformance_install_39 also fails in the same way)
Feel free to do any necessary retests on https://github.com/openshift/origin/pull/19965.
```
########## STARTING STAGE: BUILD AN OPENSHIFT-ANSIBLE RELEASE ##########
+ [[ -s /var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_gce_39/workspace/activate ]]
+ source /var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_gce_39/workspace/activate
++ export VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/4b405957477ba1b70cfacd1cf43c6d41a605fc8e
++ VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/4b405957477ba1b70cfacd1cf43c6d41a605fc8e
++ export PATH=/var/lib/jenkins/origin-ci-tool/4b405957477ba1b70cfacd1cf43c6d41a605fc8e/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ PATH=/var/lib/jenkins/origin-ci-tool/4b405957477ba1b70cfacd1cf43c6d41a605fc8e/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ unset PYTHON_HOME
++ export OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_gce_39/workspace/.config
++ OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_gce_39/workspace/.config
++ mktemp
+ script=/tmp/tmp.wgjWpOjkCM
+ cat
+ chmod +x /tmp/tmp.wgjWpOjkCM
+ scp -F /var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_gce_39/workspace/.config/origin-ci-tool/inventory/.ssh_config /tmp/tmp.wgjWpOjkCM openshiftdevel:/tmp/tmp.wgjWpOjkCM
+ ssh -F /var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_gce_39/workspace/.config/origin-ci-tool/inventory/.ssh_config -t openshiftdevel 'bash -l -c "timeout 14400 /tmp/tmp.wgjWpOjkCM"'
+ cd /data/src/github.com/openshift/openshift-ansible
+ tito_tmp_dir=tito
+ mkdir -p tito
+ tito tag --offline --accept-auto-changelog
Creating output directory: /tmp/tito
Tagging new version of openshift-ansible: 3.9.30-1 -> 3.9.31-1
Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 203, in main
    return module.main(argv)
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 671, in main
    return tagger.run(self.options)
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 114, in run
    self._tag_release()
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 136, in _tag_release
    self._check_tag_does_not_exist(self._get_new_tag(new_version))
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 502, in _check_tag_does_not_exist
    raise Exception("Tag %s already exists!" % new_tag)
Exception: Tag openshift-ansible-3.9.31-1 already exists!
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: BUILD AN OPENSHIFT-ANSIBLE RELEASE [00h 00m 03s] ##########
```

**Comment by stevekuznetsov** [comment]
/cc @sdodson 

Does the tag exist in the repo itself? Or is this an AMI thing? Is the tag present in some other branch?

**Comment by jpeeler** [comment]
The tag was created yesterday - https://github.com/openshift/openshift-ansible/releases/tag/openshift-ansible-3.9.31-1

**Comment by sdodson** [comment]
@kwoodson what's up with that tag? We need to use tito so that the specfile gets bumped at the same time as tag creation.

I just tagged 3.9.32-1 to clean this up.

**Comment by sdodson** [comment]
Did this to force 3.9.32, but normally you don't need to specify the version.

```
tito tag --use-version=3.9.32
Tagging new version of openshift-ansible: 3.9.30-1 -> 3.9.32-1

Created tag: openshift-ansible-3.9.32-1
   View: git show HEAD
   Undo: tito tag -u
   Push: git push origin && git push origin openshift-ansible-3.9.32-1
```

**Comment by kwoodson** [comment]
@sdodson I didn't do anything out of the ordinary. How do those tags get created? I merged a pr for Azure.

**Comment by jpeeler** [comment]
This has fixed the problem, thanks!

**Comment by sdodson** [comment]
@jupierce I think something is going on with tagging, these tags all tag just a random commit with no corresponding specfile version bump is that expected? This causes the origin ci processes to attempt a local tag that points at a version that may already exist.

https://github.com/openshift/openshift-ansible/releases/tag/openshift-ansible-3.9.31-1
https://github.com/openshift/openshift-ansible/releases/tag/openshift-ansible-3.10.0-0.67.0
https://github.com/openshift/openshift-ansible/releases/tag/openshift-ansible-3.10.0-0.66.0
https://github.com/openshift/openshift-ansible/releases/tag/openshift-ansible-3.10.0-0.65.0

Where as this one looks as expected
https://github.com/openshift/openshift-ansible/releases/tag/openshift-ansible-3.10.0-0.64.0

I'd initially thought that @kwoodson tagged something randomly but seeing that one of the bad tags is attributed to me and I don't recall creating it I think the CI jobs must be doing something weird.

**Comment by jupierce** [comment]
@sdodson CD was working on moving openshift-ansible to be a "normal" RPM (just like other components). Other components don't get their spec file incremented right now.

@tbielawa @adammhaile @markllama - This is resulting from new oit based openshift-ansible RPM build. oit will need to update the spec file for this component in order to not break CI.

**Comment by sdodson** [comment]
s/normal/abnormal/ FTFY
The fact that we're producing builds with versions and tags that aren't reflected in the specfile is an aberration that only OpenShift has.

@stevekuznetsov I guess one way we could resolve this is to force CI jobs to generate some tag that is never going to conflict like 3.10.0-90000

**Comment by markllama** [comment]
@sdodson I think per @jupierce this is a regression introduced when we switched the openshift-ansible RPM build from custom code in Groovy to use the OIT rpms:build task.  I'll look back at the refactored code and see If I can find what logic did this correctly before.

**Comment by stevekuznetsov** [comment]
@sdodson sure, we could make that tag. IIRC it's just in the `tito` call in the job

**Comment by markllama** [comment]
PR: https://github.com/openshift/aos-cd-jobs/pull/1461/files

**Comment by markllama** [comment]
PR merged.  Need confirmation.

**Comment by tbielawa** [comment]
@stevekuznetsov @sdodson close this out if you decide the fix did the :+1: needful

**Comment by jpeeler** [comment]
It did not, it has broken things again.

**Comment by sdodson** [comment]
@tbielawa 
It looks like setting the release strips the '.el7' from the RPM Release. The build/tag step produces `openshift-ansible-3.10.1-9999.git.0.3c903c2` but the install wants `openshift-ansible-3.10.1-9999.git.0.3c903c2.el7`

**Comment by jupierce** [comment]
@sdodson Updated with https://github.com/openshift/aos-cd-jobs/pull/1462

**Comment by jpeeler** [comment]
It's still failing - https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/12241/consoleFull#198243902558b6e51eb7608a5981914356

**Comment by jupierce** [comment]
@jpeeler Can't explain why the original push didn't work, but I pushed this time, checked that the job was corrected and it is getting further now: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/12242/consoleFull

**Comment by jpeeler** [comment]
Great, thanks for the retest. It merged, so all must be well.

**Comment by tbielawa** [comment]
Alright then folks, is there general consensus now that this is working? Nobody seeing anything "wrong" or mistagged or generally :confused: ? Ready to close this issue out?

@stevekuznetsov @sdodson @jpeeler

**Comment by markllama** [comment]
jpeeler's tests and several initiated by @jupierce overnight ran to completion, built and used the openshift-ansible package.  The fix was to force a tag during the test build that had previously been forced during oit.

**Comment by jpeeler** [comment]
Yes, I'm not seeing any issues related to the tagging any more.
