### ISSUE TITLE
CI job for openshift-ansible isn't updating the spec file Version

### ISSUE THREAD

**Issue by tbielawa** [openshift/aos-cd-jobs#1491]
Copying important bits from the original issue

https://github.com/openshift/openshift-ansible/issues/8886

----

@DanyC97 fyi it seems the CI job which cuts a new release for 3.7 branch no longer update the spec file and that has an impact on us - PaaS when we create the rpms.any chance you can correct it please?

tbielawa commented a day ago Only 3.7?

DanyC97 commented 22 hours ago

@tbielawa yes, only 3.7, 3.9 looks okay so far.

 @DanyC97
 Contributor
DanyC97 commented 22 hours ago
and note @tbielawa that up until 3.7.52 it was all good so recently something went south.
thank you for looking at btw

 @DanyC97
 Contributor
DanyC97 commented 17 hours ago
@tbielawa i take back what i said, i just built a 3.10 rpm and happens the same

https://github.com/openshift/openshift-ansible/blob/release-3.10/openshift-ansible.spec#L12-L13

**Comment by markllama** [comment]
Re openshift/openshift-ansible#8886  - I'm waiting for @smarterclayton  and @tbielawa to decide on the best course of action.

**Comment by tbielawa** [comment]
@markllama I think clayton got back to you on that

"At this point it would be better if you modify the spec file. For common components, we pass variables to the spec file rather than updating them and committing them."
