### ISSUE TITLE
'Ensure libselinux-python is installed' base image failure

### ISSUE THREAD

**Issue by kargakis** [openshift/aos-cd-jobs#1531]
```
TASK [openshift_repos : Ensure libselinux-python is installed] *****************
Friday 20 July 2018  14:28:25 +0000 (0:00:00.046)       0:04:07.643 *********** 
fatal: [40.121.68.105]: FAILED! => {"msg": "The conditional check 'not openshift_is_atomic' failed. The error was: error while evaluating conditional (not openshift_is_atomic): 'openshift_is_atomic' is undefined\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/roles/openshift_repos/tasks/main.yaml': line 6, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  # TODO: This needs to be removed and placed into a role\n  - name: Ensure libselinux-python is installed\n    ^ here\n"}
```
https://ci.openshift.redhat.com/jenkins/job/azure_build_base_image_centos/82/consoleFull#172018562258b6e51eb7608a5981914356

Started happening two days ago

@openshift/sig-azure

**Comment by kargakis** [comment]
Both centos and rhel jobs fail

https://ci.openshift.redhat.com/jenkins/job/azure_build_base_image_rhel/87/consoleFull#172018562258b6e51eb7608a5981914356

**Comment by kargakis** [comment]
Also something to keep in mind, our node image builds are stalled because base image builds fail. We should probably run node image builds independently as well as child jobs to base builds.

**Comment by kargakis** [comment]
PR jobs are also broken because of this.

**Comment by jim-minter** [comment]
@kargakis @kwoodson now https://github.com/openshift/openshift-ansible/pull/9305 is merged can this be closed?

**Comment by kargakis** [comment]
This seems fixed and some of our jobs are back to green after a long time! Thanks @kwoodson !

**Comment by kargakis** [comment]
> This seems fixed and some of our jobs are back to green after a long time! Thanks @kwoodson !

Heh, I guess we have green jobs because of https://github.com/openshift/aos-cd-jobs/pull/1537
