### ISSUE TITLE
failure with devexp bump jenkins version

### ISSUE THREAD

**Issue by gabemontero** [openshift/aos-cd-jobs#1599]
So after getting 4.0 as an option for https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-bump-version/

When I ran job https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-bump-version/23/console it looks like it downloaded the new jenkins war just fine, but i then bombed out.

That last chuck on logs:

```
2018-10-01 15:14:13 (2.90 MB/s) - ‘jenkins.war’ saved [75714886/75714886]

From ssh://pkgs.devel.redhat.com/rpms/jenkins
 * branch            rhaos-3.7-rhel-7 -> FETCH_HEAD
fatal: refusing to merge unrelated histories
[Pipeline] }
[Pipeline] // stage
[Pipeline] mail
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 128
Finished: FAILURE

Page generated: Oct 1, 2018 3:19:03 PM EDTREST APIJenkins ver. 2.73.1
```

In looking at https://github.com/openshift/aos-cd-jobs/blob/master/jobs/devex/jenkins-bump-version/bump-jenkins.sh#L53 I'm wondering if the reference to 3.7 rhaos is now too out of date.

But I just don't have enough context wrt what this is doing to know for sure.

Help @tbielawa @adammhaile ?

@bparees fyi

**Comment by adammhaile** [comment]
@gabemontero I don't really know anything about this job but looks like you need to add `--allow-unrelated-histories` to your git commands.

**Comment by gabemontero** [comment]
ok thanks @adammhaile .... I'll start constructing a PR.

@jupierce - know you don't own this anymore, but as the originator of this internal pipeline job, any quick guidance or table setting you could provide?

thanks
