### ISSUE TITLE
No longer seeing emails for auth extended test failures

### ISSUE THREAD

**Issue by enj** [openshift/aos-cd-jobs#1607]
After the change made in #1598, I am no longer seeing failure emails.

Per https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_gssapi/584/consoleFull#-47159270058b6e51eb7608a5981914356 I can see:

`Sending e-mails to: aos-auth-team@redhat.com`

@ericavonb has noted that the mailing list has no restrictions.

/assign @stevekuznetsov 
@openshift/sig-security

**Comment by stevekuznetsov** [comment]
I think this is as the default configuration does not "Send e-mail for every unstable build" and your job is consistently red. I'll update that.
