### ISSUE TITLE
Metrics Release 3.10.0 is not on Docker Hub

### ISSUE THREAD

**Issue by ceagan** [openshift/aos-cd-jobs#1617]
There appears to be a build/push issue with OpenShift Metrics 3.10 and might be related to the code in this project. I'm not sure, but could someone on this project please give it a quick look?

https://github.com/openshift/openshift-ansible/issues/9948
https://github.com/openshift/origin-metrics/issues/429
https://ci.openshift.redhat.com/jenkins/job/push_origin_metrics_release_310/

**Comment by bilalx20** [comment]
solution here openshift/origin-metrics#429

**Comment by ceagan** [comment]
> 
> 
> solution here [openshift/origin-metrics#429](https://github.com/openshift/origin-metrics/issues/429)

@bilalcaliskan Unfortunately, the only solution on that issue, which I also referenced in my original post, is a workaround that installs version 3.11. Did you find something on that issue that I'm not seeing?

**Comment by bilalcaliskan** [comment]
@ceagan 
https://github.com/openshift/origin-metrics/issues/429#issuecomment-418271287 suggests that to install metrics-3.11 releases for openshift-3.10. You should change your inventory file and re-initialize cluster. You will get the idea if you click the link.
