### ISSUE TITLE
build/advisory  should bugzilla login before elliott create-placeholder

### ISSUE THREAD

**Issue by shiywang** [openshift/aos-cd-jobs#2000]
https://localhost:8888/job/aos-cd-builds/job/build%252Fadvisories/9/console

**Comment by shiywang** [comment]
currently, we still waiting for the for Bugzilla bot account to be available on buildvm.

**Comment by thiagoalessio** [comment]
I think that was solved by either @tbielawa or @jupierce . Can we close this issue?

**Comment by tbielawa** [comment]
I think this is good to close. We have the account set up using a stored API key now. No more logging in required.
