### ISSUE TITLE
AWS Failures in origin-ci-tool not surfaced back up to end user in a sane way

### ISSUE THREAD

**Issue by smarterclayton** [openshift/aos-cd-jobs#211]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_install/279/consoleFull#-123995087358b6e51eb7608a5981914356

**Comment by smarterclayton** [comment]
The AMI doesn't have an `origin` user, which oct expects

@stevekuznetsov @jupierce @jhadvig @dobbymoodge did we fiddle with the AMI in the last day or so?  Started failing friday afternoon

**Comment by smarterclayton** [comment]
Actually, it *does* have the origin user, but I can't SSH in with that user, only with root.

**Comment by smarterclayton** [comment]
Recreate:

```
oct provision remote all-in-one --os rhel --stage base --provider aws --discrete-ssh-config --name A_NAME
oct sync remote origin --branch master
```

**Comment by stevekuznetsov** [comment]
Does the job creating `base` have `oct prepare user` as a step? This was working fine last week...

**Comment by stevekuznetsov** [comment]
Looks like it does... John any chance the new AMI pruning was too liberal? AMIs from more than two weeks ago won't have the right SSH setup for that user.

**Comment by stevekuznetsov** [comment]
Yeah, @dobbymoodge the pruning seems to have deleted all of the `(operating_system=rhel,image_stage=base,ready=yes)` images since Feb 13, so the latest AMIs we have are too old and incompatible. We need to turn off the pruning job and get new ones built.

**Comment by stevekuznetsov** [comment]
The pruning _has_ kept around the last two `ready=no` ones, though...

**Comment by stevekuznetsov** [comment]
I've manually tagged one of the failed `image_stage=base` as `ready=yes` -- the issues that the job was having (Docker not being started) are not present when I just start one manually.

**Comment by dobbymoodge** [comment]
@stevekuznetsov huh, that's really strange. It should keep around the latest two of any combo. ... but it just ran and I can see that's not what's happening.

I'll disable the job for now and take a look at the code today/tomorrow morning.

**Comment by stevekuznetsov** [comment]
I think it is keeping last two regardless of `ready=` value.

**Comment by smarterclayton** [comment]
The revert got us back to working - and then at 3:15pm (about) we stopped working on a new failure mode - instance doesn't respond to SSH.  Couldn't tell whether this was the new AMI (ami-e2a937f4) being used, or whether another behavior changed.

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_install/280/ started, https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_install/281/ failed to get the instance.

failing with:

```

**Comment by stevekuznetsov** [comment]
Taking a look.

**Comment by stevekuznetsov** [comment]
I can reproduce it but I think it's an AWS error? I see:

```
Instance state: terminated
State transition reason: Server.InternalError
State transition reason message: Client.VolumeLimitExceeded: Volume limit exceeded
```

**Comment by stevekuznetsov** [comment]
Well, still an error on our end:

> Client.VolumeLimitExceeded: The limit on the number of EBS volumes or total storage was exceeded. Decrease usage or request an increase in your limits.

**Comment by dobbymoodge** [comment]
That might be due to the prune script running *just one more time*, which is what I was referring to in my previous comment. It removed an older AMI though:

> Removing old AMI: ami-7888176e - ami_build_origin_int_rhel_base_71

**Comment by stevekuznetsov** [comment]
Looks like we have too many instances in "terminate" state -- did you also disable the reaper?

**Comment by stevekuznetsov** [comment]
We have ~900 EBS volumes in use right now, but one I just looked at is attached to a stopped instance named "terminate" that was created as part of a job run.

**Comment by stevekuznetsov** [comment]
But there's also 200 stopped but not renamed `test_pull_request*` instances... maybe the failure hook on the Jenkins jobs isn't firing somehow?

**Comment by stevekuznetsov** [comment]
Looks like when a post-job step fails it skips all the rest of the post-job steps even though they are clearly marked as "run on failure". I'll try to clean this up.

**Comment by stevekuznetsov** [comment]
They're all renamed to `teminate` but aren't getting cleaned up.

**Comment by dobbymoodge** [comment]
Yeah, I'm not sure why those haven't been getting terminated. This has been happening since long before my changes though. I wonder if it has something to do with how they're being created or some other aspect of their lifecycle.

**Comment by smarterclayton** [comment]
Resolved the core issue, will leave this open for messages.

**Comment by stevekuznetsov** [comment]
That issue should be opened against the `ec2` module in the Ansible repo, we just parrot that error output to the user.
