### ISSUE TITLE
make -j makes CI logs harder to read

### ISSUE THREAD

**Issue by jim-minter** [openshift/aos-cd-jobs#257]
Using `make -j` at https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_branch_origin_check.yml#L19 makes CI logs harder to understand as the output of test-unit and test-cmd is interposed.

Would a PR to remove this "-j" be acceptable?

**Comment by jim-minter** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1441/consoleFull is an example of this happening: there's 2000 lines of go unit test output breaking up a cmd test failure - search for "/go/sRunning" in the output to see what I mean.

**Comment by stevekuznetsov** [comment]
Sorry -- this slipped through my cracks. I don't think it is tenable today to serialize these tasks. However, we should just break them up into separate jobs a la #408
