### ISSUE TITLE
git rebase -i fails on empty commits

### ISSUE THREAD

**Issue by kargakis** [openshift/aos-cd-jobs#259]
We need to find a way for devs to remove CARRY commits without force-pushing. Creating a revert of a CARRY commit as a SQUASH does not work because `git rebase -i` doesn't know what to do with the empty commit. We may want to add logic and identify empty commits before actually doing the rebase and drop all those commits automatically.

Found in https://github.com/openshift/aos-cd-jobs/pull/258

@stevekuznetsov @jupierce

**Comment by stevekuznetsov** [comment]
```
git rebase -i --keep-empty
```

Followed by 

```
for commit_sha in ${some_range}; do
    if [[ -z "$( git diff "${commit_sha}" )" ]]; then
        # empty commit
    fi
done
```

?
