### ISSUE TITLE
auto-sync openshift/kubernetes

### ISSUE THREAD

**Issue by deads2k** [openshift/aos-cd-jobs#279]
The openshift level of kubernetes carries multiple patches.  Sometimes we need  to be able to pull a level of kube that matches our vendor tree.  We should automate the process of keeping these patches up to date by copying the UPSTREAM commits to `openshift/kubernetes`, then auto-creating a `bump(k8s.io/kubernetes):<openshift/kuberenetes sha>` commit in openshift/origin.

`hack/move-upstream.sh` make this possible (I think), but its not set up to be run automatically.

@sttts you are well versed in bash, do you think you could put together a script that does this for us?
@stevekuznetsov once we have a script, can you wire our job?

**Comment by stevekuznetsov** [comment]
> @stevekuznetsov once we have a script, can you wire our job?

We can set up a job that triggers off of merges into Origin. Should not be hard.

**Comment by stevekuznetsov** [comment]
Any updates here?
