### ISSUE TITLE
Improve Semantics of Post-Build Tasks

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/aos-cd-jobs#352]
Today, we run a number of post-build `publishers`. As only one `org.jenkinsci.plugins.postbuildscript.PostBuildScript` can be run as a `publisher`, we end up with a block of `buildSteps` of type `hudson.tasks.Shell`. This means that if we have a post-build flow like -- generate artifacts, retrieve artifacts, fetch `systemd` journals, deprovision cloud resources -- and one of the first `hudson.tasks.Shell` fails, the rest will not run. Although the larger `org.jenkinsci.plugins.postbuildscript.PostBuildScript` is set to run regardless of whether the job failed or not, the linear flow of `hudson.tasks.Shell` will exit early on any individual failure. We can try to address this by adding `|| true` to our actions in these steps but in reality we just need a way to parameterize a `named_shell_action` so we don't always add `set -o errexit`. This way, failures will be silently ignored and all post-build tasks will run.

/cc @soltysh

**Comment by soltysh** [comment]
I need to familiarize myself with how this all machinery is working, but I'll try to hack something up.
