### ISSUE TITLE
package-dockertested: skopeo version skew breaks pre-flight checks

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/aos-cd-jobs#361]
We install `docker` using the `rhel7next*` suite of repos, which are synced from the latest RHEL 7 Extras compose in Brew. During this process, recently we are bringing in `skopeo-containers` as a dependency:

```
$ sudo yum --disablerepo=\* --enablerepo=rhel7next\* install docker
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Resolving Dependencies
--> Running transaction check
---> Package docker.x86_64 2:1.12.6-32.git88a4867.el7 will be installed
--> Processing Dependency: docker-client = 2:1.12.6-32.git88a4867.el7 for package: 2:docker-1.12.6-32.git88a4867.el7.x86_64
--> Processing Dependency: docker-common = 2:1.12.6-32.git88a4867.el7 for package: 2:docker-1.12.6-32.git88a4867.el7.x86_64
--> Processing Dependency: docker-rhel-push-plugin = 2:1.12.6-32.git88a4867.el7 for package: 2:docker-1.12.6-32.git88a4867.el7.x86_64
--> Processing Dependency: container-selinux >= 2:2.12-2 for package: 2:docker-1.12.6-32.git88a4867.el7.x86_64
--> Processing Dependency: oci-register-machine >= 1:0-3.10 for package: 2:docker-1.12.6-32.git88a4867.el7.x86_64
--> Processing Dependency: oci-systemd-hook >= 1:0.1.4-9 for package: 2:docker-1.12.6-32.git88a4867.el7.x86_64
--> Processing Dependency: skopeo-containers for package: 2:docker-1.12.6-32.git88a4867.el7.x86_64
--> Processing Dependency: libseccomp.so.2()(64bit) for package: 2:docker-1.12.6-32.git88a4867.el7.x86_64
--> Running transaction check
---> Package container-selinux.noarch 2:2.15-1.git583ca40.el7 will be installed
---> Package docker-client.x86_64 2:1.12.6-32.git88a4867.el7 will be installed
---> Package docker-common.x86_64 2:1.12.6-32.git88a4867.el7 will be installed
---> Package docker-rhel-push-plugin.x86_64 2:1.12.6-32.git88a4867.el7 will be installed
---> Package libseccomp.x86_64 0:2.3.1-2.el7 will be installed
---> Package oci-register-machine.x86_64 1:0-3.11.gitdd0daef.el7 will be installed
---> Package oci-systemd-hook.x86_64 1:0.1.7-4.gite533efa.el7 will be installed
--> Processing Dependency: libyajl.so.2()(64bit) for package: 1:oci-systemd-hook-0.1.7-4.gite533efa.el7.x86_64
---> Package skopeo-containers.x86_64 1:0.1.20-2.el7 will be installed
--> Running transaction check
---> Package yajl.x86_64 0:2.0.4-4.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================================================================================
 Package                                 Arch                   Version                                     Repository                        Size
===================================================================================================================================================
Installing:
 docker                                  x86_64                 2:1.12.6-32.git88a4867.el7                  rhel7next-extras                  14 M
Installing for dependencies:
 container-selinux                       noarch                 2:2.15-1.git583ca40.el7                     rhel7next-extras                  29 k
 docker-client                           x86_64                 2:1.12.6-32.git88a4867.el7                  rhel7next-extras                 3.3 M
 docker-common                           x86_64                 2:1.12.6-32.git88a4867.el7                  rhel7next-extras                  76 k
 docker-rhel-push-plugin                 x86_64                 2:1.12.6-32.git88a4867.el7                  rhel7next-extras                 1.5 M
 libseccomp                              x86_64                 2.3.1-2.el7                                 rhel7next                         56 k
 oci-register-machine                    x86_64                 1:0-3.11.gitdd0daef.el7                     rhel7next-extras                 1.0 M
 oci-systemd-hook                        x86_64                 1:0.1.7-4.gite533efa.el7                    rhel7next-extras                  30 k
 skopeo-containers                       x86_64                 1:0.1.20-2.el7                              rhel7next-extras                 7.9 k
 yajl                                    x86_64                 2.0.4-4.el7                                 rhel7next                         39 k

Transaction Summary
===================================================================================================================================================
Install  1 Package (+9 Dependent packages)
```

This means when we run pre-flight checks in the installer that try to install and use `skopeo`, they need to be grabbing the bleeding edge version from the `rhel7next*` repositories as well, otherwise they fail like so:

```
    Failure summary:
     
      1. Host:     localhost
         Play:     Verify Requirements
         Task:     openshift_health_check
         Message:  One or more checks failed
         Details:  check "docker_image_availability":
                   Some dependencies are required in order to check Docker image availability.
                   Error: Package: 1:skopeo-0.1.19-1.el7.x86_64 (oso-rhui-rhel-server-extras)
                              Requires: skopeo-containers = 1:0.1.19-1.el7
                              Installed: 1:skopeo-containers-0.1.20-2.el7.x86_64 (@rhel7next-extras)
                                  skopeo-containers = 1:0.1.20-2.el7
                              Available: 1:skopeo-containers-0.1.17-0.7.git1f655f3.el7.x86_64 (oso-rhui-rhel-server-extras)
                                  skopeo-containers = 1:0.1.17-0.7.git1f655f3.el7
                              Available: 1:skopeo-containers-0.1.17-1.el7.x86_64 (oso-rhui-rhel-server-extras)
                                  skopeo-containers = 1:0.1.17-1.el7
                              Available: 1:skopeo-containers-0.1.18-1.el7.x86_64 (oso-rhui-rhel-server-extras)
                                  skopeo-containers = 1:0.1.18-1.el7
                              Available: 1:skopeo-containers-0.1.19-1.el7.x86_64 (oso-rhui-rhel-server-extras)
                                  skopeo-containers = 1:0.1.19-1.el7
                   
     
    The execution of "/usr/share/ansible/openshift-ansible/playbooks/byo/config.yml"
    includes checks designed to fail early if the requirements
    of the playbook are not met. One or more of these checks
    failed. To disregard these results, you may choose to
    disable failing checks by setting an Ansible variable:
     
       openshift_disable_check=docker_image_availability
     
    Failing check names are shown in the failure details above.
    Some checks may be configurable by variables if your requirements
    are different from the defaults; consult check documentation.
    Variables can be set in the inventory or passed on the
    command line using the -e flag to ansible-playbook.
```

We should probably add a `oct prepare skopeo` command (`oct` should be well-formed for this, but maybe we want a more generic `oct prepare package`?). Then, we need to add logic to the `package-dockertested` job to install `skopeo` from `rhel7next*` with the new command, as it does for `docker`. Furthermore, we need to update the call to the [`update-dockertested-repo.sh`](https://github.com/openshift/aos-cd-jobs/blob/master/jobs/package-dockertested/Jenkinsfile#L133) script to add to the `dockertested` repo the package containing `skopeo`. Then, we can finally update the job configuration for [`ami_build_origin_int_rhel_base`](https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/ami_build_origin_int_rhel_base.yml) so that new base AMIs will install the correct version of `skopeo`.

**Comment by stevekuznetsov** [comment]
@sosiouxme @rhcarvalho please triage this. Today, fixing this issue is a blocker for  getting new versions of Docker into the CI stream, so if you feel like you will not have the bandwidth to tackle it this week we can just turn off the check.

**Comment by sosiouxme** [comment]
I can make a PR to disable this check for now to unblock testing with `rhel7next docker`.

Who has been driving getting `rhel7next docker` into use in CI? It seems like it would be way more efficient for them to update that to pull in `rhel7next skopeo` as well than for me to try to figure out how to do everything @stevekuznetsov described above. And it feels like a better owner for this problem - we're just trying to consume `skopeo` and don't care how it gets there.

**Comment by stevekuznetsov** [comment]
This job and the workflow above _are_ the mechanism for getting the latest `docker` into our CI. We can't install from `rhel7next*` on the normal CI AMIs as any repo we install from we basically need to always remain on for the future, and we cannot safely rely on the latest Extras compose. This is why the `package-dockertested` job exists to take the bleeding edge `docker`, test it, and when it's safe, tag it into the tested repository for consumption by the normal CI AMIs.

**Comment by sdodson** [comment]
What if rather than trying to chase dependencies the test job pulls from a candidate rhel7next and once tests pass it then publishes that repo to a location that's used by jobs and that repo is left enabled in the AMI? The test process would need to use an alternate location but same reponame and be sure to clear its caches before sealing the image.

**Comment by stevekuznetsov** [comment]
You mean instead of promoting specific packages like we do today, instead promote the entire `rhel7next*` ecosystem all together? We have some cards to build such a system but just have not had time to think it all through yet.

**Comment by sosiouxme** [comment]
We can scrum about who'll take on the CI updates. /cc @brenton 

@juanvallejo feel like getting to know our CI better? :-P

**Comment by sdodson** [comment]
@stevekuznetsov ... or mirror the repo locally to the AMI and then make the repo definition point at the local filesystem. Not sure how large the repo is or if there are any limits on the ami size.

**Comment by rhcarvalho** [comment]
Discussed with @sosiouxme on IRC that we can keep the `docker_image_availability` disabled for the `dockertested` job.

Unless anybody plans to work on the discussed solution involving yum repos, this issue can be closed.

**Comment by stevekuznetsov** [comment]
@rhcarvalho the check will need to be disabled for _all_ jobs as when we have the newer `docker` installed, it will have the same conflict with `skopeo-containers` and the check will not be able to install `skopeo` from non-bleeding edge repos. If you guys want this check to be running, this is a hard pre-requisite.

**Comment by stevekuznetsov** [comment]
Actually as per [this build info](https://brewweb.engineering.redhat.com/brew/rpminfo?rpmID=4748671) it looks like the `%requires` from Docker to `skopeo-containers` is not versioned, so we _might_ be able to get away with version skew between the two packages. @lsm5 @runcom or @rhcarvalho I feel like we need to understand the dependency between these two packages better to know if we are going to be OK tolerating this skew or, as above, we are going to want to bring in `skopeo` from the newest compose as well
