### ISSUE TITLE
VM changed to make registry.access.redhat.com the default

### ISSUE THREAD

**Issue by smarterclayton** [openshift/aos-cd-jobs#388]
Caused failures in jobs:

https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/292/consoleText

because registry.access.redhat.com is not pushable.  We shouldn't be using registry.access.redhat.com as the default registry for the AMI VM, changing the default registry in docker is a bad idea.

**Comment by stevekuznetsov** [comment]
Jobs are setting enterprise deployment type and this is coming from the installer, not here.
