### ISSUE TITLE
Jenkins parameters w/o any default value should not be unset

### ISSUE THREAD

**Issue by kargakis** [openshift/aos-cd-jobs#393]
Jenkins parameters w/o any default values are considered unset by our stages so we cannot use them at all (because of `set -u`).

See https://github.com/openshift/aos-cd-jobs/issues/391#issue-240451587

@stevekuznetsov

**Comment by stevekuznetsov** [comment]
How do you think we should get around this? It's default Jenkins behavior AFAICT.

**Comment by kargakis** [comment]
Either https://wiki.jenkins.io/display/JENKINS/Export+Parameters+Plugin may work or we can query Jenkins params from inside which sounds meh.

**Comment by kargakis** [comment]
As a workaround for now, we can default to `<none>` (what I did in the new fork_ami job).

**Comment by kargakis** [comment]
> or we can query Jenkins params from inside which sounds meh.

Hm, if we can't have the build id then this is not possible. Chicken-egg problem.

**Comment by stevekuznetsov** [comment]
What is a concrete example of this failure? When the job should either do the old flow (with `$ORIGIN_PULL_ID`) or the new one (with `$PULL_REFS`)? Why not just:

```sh
if [[ -n "${PULL_REFS:-}" ]]; then
    # run k8s-style stuff
elif [[ -n "${ORIGIN_PULL_ID:-}" ]]; then
    # run origin-style stuff
else
    # uh oh
fi
```

**Comment by kargakis** [comment]
If that won't break when PULL_REFS is unset, then it's fine.

**Comment by stevekuznetsov** [comment]
Yep, that is correct way to check for variables being set and will play nice with `set -o errexit` and `set -o nounset`.
