### ISSUE TITLE
Make the `process-pull-requests` (Rosie) calls in the jobs get skipped if $PULL_REFS is set

### ISSUE THREAD

**Issue by kargakis** [openshift/aos-cd-jobs#437]
Extracted from e-mail discussion @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Should be able to do

```sh
if [[ -z "${PULL_REFS:-}" ]]; then
    process-pull-requests ...
fi
```

We'll need to make the change in `sjb/templates/test_case.xml.

**Comment by kargakis** [comment]
Is this template generated from somewhere or we need to do the change directly into it?

**Comment by kargakis** [comment]
Btw I only see `test_pull_requests` being called in there.

**Comment by stevekuznetsov** [comment]
The template is the source of truth, no need to update anywhere. Yes, sorry, `test_pull_requests` is the name of the Ruby script.
