### ISSUE TITLE
Failure cause management support in sjb

### ISSUE THREAD

**Issue by kargakis** [openshift/aos-cd-jobs#446]
I am wondering if we can store our failure causes inside config in this repo as opposed to having them buried inside Jenkins

@stevekuznetsov

**Comment by stevekuznetsov** [comment]
The [plugin page](https://wiki.jenkins.io/plugins/servlet/mobile?contentId=65667716#content/view/65667716) says we can serialize the knowledge base as XML. Unclear if hot-reload of that is supported.
