### ISSUE TITLE
base_ami is broken - centos_paas repo needs go1.8

### ISSUE THREAD

**Issue by kargakis** [openshift/aos-cd-jobs#450]
https://ci.openshift.redhat.com/jenkins/view/All/job/ami_build_origin_int_rhel_base/174/consoleFull#9078238345898c58db7602c31c0eab717

@stevekuznetsov any idea who is responsible for updating https://cbs.centos.org/repos/paas7-openshift-origin36-candidate/x86_64/os/?

cc: @brenton

**Comment by stevekuznetsov** [comment]
I was going to handle this when I got back, but if we next it sooner, @sdodson can add in the Go RPM and we can switch to installing it in the AMI

**Comment by kargakis** [comment]
Fixed by https://github.com/openshift/aos-cd-jobs/pull/469
