### ISSUE TITLE
Batch merge link points to upstream prow

### ISSUE THREAD

**Issue by deads2k** [openshift/aos-cd-jobs#462]
The batch merge link on https://origin-sq-status-ci.svc.ci.openshift.org/#/queue points to https://prow.k8s.io/?type=batch

@kargakis @stevekuznetsov I don't know what repo to open these against.

**Comment by stevekuznetsov** [comment]
@deads2k either this one or openshift/test-infra

**Comment by kargakis** [comment]
Fix merged in https://github.com/kubernetes/test-infra/pull/3703 - will close once we redeploy our SQ instance with it.

**Comment by stevekuznetsov** [comment]
@kargakis do we want to rebase ?

**Comment by kargakis** [comment]
If there are no PRs in the queue, we could do it. Otherwise, I would wait for https://github.com/kubernetes/test-infra/pull/3735 and your PR to land so we can drop the patches we carry.

**Comment by stevekuznetsov** [comment]
> our PR to land

for bot name?

**Comment by kargakis** [comment]
Yeah, that's the other patch, right? Although I am also patching the approve no-issue thingy so we still need an additional fix to drop that one too... sigh. I guess we can redeploy but we need a card to drop the patches, I don't want to accumulate any tech-debt.

**Comment by kargakis** [comment]
Fixed
