### ISSUE TITLE
old test jobs are not cancelled when new commits are pushed

### ISSUE THREAD

**Issue by bparees** [openshift/aos-cd-jobs#466]
I pushed a commit, tagged the PR to run extended tests, then pushed a new commit.  The old extended test job was not canceled (but a new job was started to run the new commit).

PR:
https://github.com/openshift/origin/pull/15439

old job:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_templates/3/
new job:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_templates/4

**Comment by stevekuznetsov** [comment]
Prow did have a duration stamp for the old job though so it did consider it finished

**Comment by kargakis** [comment]
Yeah, eventually I want to get cancellation in (abort a job once a new job for the same PR starts). Note that Rosie was no different than what Prow is doing today in that regard.

**Comment by bparees** [comment]
> Note that Rosie was no different than what Prow is doing today in that regard.

yup, except that Prow now starts the new job immediately, which is both good(yay, fast!), and bad (bad because it encourages people to leave their old jobs running.  Before you were motivated to cancel the old job in order to get your new job to start sooner).

**Comment by kargakis** [comment]
You can still cancel the job in Jenkins if you care enough.

**Comment by stevekuznetsov** [comment]
> Before you were motivated to cancel the old job in order to get your new job to start sooner).

I would bet my yearly salary no more than four people ever pushed that button.

**Comment by bparees** [comment]
> You can still cancel the job in Jenkins if you care enough.

right, but previously people had a reason to care beyond saving us some money.  now they don't.  that's why i think it's more important now.

I am not claiming this is hugely critical.

> I would bet my yearly salary no more than four people ever pushed that button.

i will take that bet.  it may not be a lot, but it is more than 4 :)

**Comment by stevekuznetsov** [comment]
@kargakis if you can confirm this is just Prow behavior with Jenkins, I will close this and push it upstream

**Comment by bparees** [comment]
it was also easier to track down the old job before, because you had the comment to the old job which you had to cancel before you'd get a new job.  now the status immediately points to the new job, so you have to go to prow(?) if you want to go find the old job for your PR and cancel.

**Comment by bparees** [comment]
one more reason:  previously due to the rosie behavior, i could push 5 commits and potentially only trigger one test run.  Now i'm going to get 5 test runs even though i don't care about 4 of them.  So there is going to be added cost if we aren't canceling them, even aside from whatever people do manually.

**Comment by kargakis** [comment]
Test aggregation for a PR is effectively what Gubernator is about. 

Yes, this is a prow issue. I think there is already an issue upstream or at least it has been discussed somewhere. Leave the issue open and tomorrow I will try to link the related discussion and close.

**Comment by kargakis** [comment]
> one more reason: previously due to the rosie behavior, i could push 5 commits and potentially only trigger one test run. Now i'm going to get 5 test runs even though i don't care about 4 of them. So there is going to be added cost if we aren't canceling them, even aside from whatever people do manually.

If you push them at the same time, this shouldn't be an issue I think. If you push them separately then yes, you will likely trigger a separate test run for each push.

**Comment by bparees** [comment]
> If you push them separately then yes, you will likely trigger a separate test run for each push.

that's the case i mean.  "oops, noticed a typo" [push] "oops, forget this other spot" [push], etc.

**Comment by kargakis** [comment]
Upstream issue is https://github.com/kubernetes/test-infra/issues/3209
