### ISSUE TITLE
Create a new job that pushes origin-gce in dockerhub

### ISSUE THREAD

**Issue by kargakis** [openshift/aos-cd-jobs#474]
Or update the existing job that pushes releases in dockerhub to also push origin-gce (if that makes sense).

@jhadvig @smarterclayton @stevekuznetsov

**Comment by smarterclayton** [comment]
zz-origin-gce is the gate that prevents openshift-ansible changes from
impacting jobs, by controlling  when a new origin-gce image containing new
openshift-ansible code is added.  It's probably better to be a different
job.
