### ISSUE TITLE
Allow for running extended tests with a focus

### ISSUE THREAD

**Issue by miminar** [openshift/aos-cd-jobs#483]
I'd really like to run registry and pruning related tests for registry code changes like before:

```
[testextended][extended:core(ImagePrun|registry)]
```

**Comment by stevekuznetsov** [comment]
This is probably not going to happen. What we _can_ do is write a non-blocking job `/test registry` or something that you guys can use that encodes a focus you use often -- can you provide one? I'll make the job

**Comment by miminar** [comment]
@stevekuznetsov My favorite focus is `'ImagePrune|registry|ImageLookup|ImageQuota'`. It could be simplified to `Image|registry`.

**Comment by stevekuznetsov** [comment]
@miminar ask and you shall receive :)

**Comment by miminar** [comment]
Thanks man! Resolved.
