### ISSUE TITLE
Base AMI is still broken

### ISSUE THREAD

**Issue by kargakis** [openshift/aos-cd-jobs#504]
May be related to the recent changes in the ingtegration job

cc: @stevekuznetsov @deads2k 

https://ci.openshift.redhat.com/jenkins/view/AMIs/job/ami_build_origin_int_rhel_base/188/consoleFull#-3492724395898c58db7602c31c0eab717

**Comment by deads2k** [comment]
I don't know what this does.

**Comment by kargakis** [comment]
https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/ami_build_origin_int_rhel_base.yml

**Comment by stevekuznetsov** [comment]
Fixed in f1aff0c0fe5062c642b7470dc8dc2133e5dd00fd

**Comment by kargakis** [comment]
![thank_you_based_god_nick](https://user-images.githubusercontent.com/3900799/28928264-1a239ec8-786d-11e7-9dad-48910d8da9f0.jpg)
