### ISSUE TITLE
Stream rcm scripts for stage-to-prod and use pipeline-scripts/buildlib.groovy

### ISSUE THREAD

**Issue by jupierce** [openshift/aos-cd-jobs#539]
@adammhaile Please use new rcm script streaming method for: 
https://github.com/openshift/aos-cd-jobs/blob/master/jobs/build/stage-to-prod/Jenkinsfile

This is encapsulated in a new Groovy library I'm writing and I'd like to start using everywhere: https://github.com/openshift/aos-cd-jobs/blob/master/jobs/build/ocp/Jenkinsfile#L377

Which is loaded: 
https://github.com/openshift/aos-cd-jobs/blob/master/jobs/build/ocp/Jenkinsfile#L55

And defined: https://github.com/openshift/aos-cd-jobs/blob/master/pipeline-scripts/buildlib.groovy

**Comment by adammhaile** [comment]
This has been done for a long time and should be closed.
