### ISSUE TITLE
In GCE CI testing, don't allow stage binaries to be paired with master images?

### ISSUE THREAD

**Issue by jim-minter** [openshift/aos-cd-jobs#738]
Build break https://github.com/openshift/origin/issues/16882 was caused by a binary under test built from `stage` being paired with incompatible newer docker images from `master`.

I understand that on GCE, a binary under test may see older docker images, and that this artifact helps somewhat in showing system upgradability without requiring lockstep.

@smarterclayton is the intention to do this the other way around as well?  If not, can we have separate sets of images for separate branches in GCE?

**Comment by stevekuznetsov** [comment]
>  If not, can we have separate sets of images for separate branches in GCE?

I am currently working on building the pipelines to give us version-branched images for `openshift/origin-gce`. It's just not something we have gotten around to yet.

**Comment by smarterclayton** [comment]
We're also getting close to (but do not have yet) the pipelines to build
images - once we have those we'll deploy GCP clusters completely from
openshift (source images and RPMs)
