### ISSUE TITLE
refresh-images should hard fail if VERSION_OVERRIDE does not start with "v"

### ISSUE THREAD

**Issue by adammhaile** [openshift/aos-cd-jobs#859]
$subject

@jupierce I would assign to me but apparently I don't have rights. Please assign to me.

**Comment by stevekuznetsov** [comment]
Why do work when we have robots to do that for you?

**Comment by adammhaile** [comment]
@stevekuznetsov Didn't know you could do that :)

**Comment by jupierce** [comment]
https://github.com/openshift/aos-cd-jobs/commit/932b4cf959dc653bab53a51b331a5a9b39ec4a7b
