### ISSUE TITLE
base AMI is broken

### ISSUE THREAD

**Issue by kargakis** [openshift/aos-cd-jobs#922]
For two months now.

https://ci.openshift.redhat.com/jenkins/view/AMIs/job/ami_build_origin_int_rhel_base/473/consoleFull#161232730158b6e51eb7608a5981914356

@stevekuznetsov seems like the docker registry is not built correctly for the integration test?

cc: @dmage @legionus

**Comment by stevekuznetsov** [comment]
That's a new failure -- the bigger issue has been the Idling thing with no network plugin that Ben was looking into. There's a PR open to Origin to fix that.
