### ISSUE TITLE
Make it easy to run any job and leave the vm running at the end for fault diagnosis

### ISSUE THREAD

**Issue by jim-minter** [openshift/aos-cd-jobs#965]
If a flaking test can't be replicated locally, it is challenging to manually recreate a remote environment to replicate the test failure.  At the moment the easiest route seems to be to clone a job in jenkins and remove all the post-run triggers.  It would be great if all jobs could have an option that prevented clean-up, so that a developer could ssh into the VM after a test failure and diagnose the issue.

**Comment by stevekuznetsov** [comment]
You're looking for a parameter in Jenkins that would stop cleanup? I'm afraid getting all the inputs to Jenkins is going to be a pain -- lots of SHA stuff to copy over to act as if you are Prow when triggering it. Right now the simplest way to stop a job from being cleaned up is just to rename the instance in EC2 while it's being run. Is that low-effort enough to make your life easier right now?
